### ISSUE TITLE
Refactor apps; fix signature bugs.

### ISSUE THREAD

**Issue by DmytroLitvinov** [DmytroLitvinov/kuna#6]
- [x] Remove coverage badge
- [x] Add basic usage in README.rst
- [ ] Test all user methods

**Comment by egorsmkv** [comment]
Привет, @DmytroLitvinov

Библиотека по не работает? Получаю такую ошибку:

```
kuna.kuna.APIError: Signature 296de3d730af684f19bc3ea1c0fe46ab19edc86c12d7238c22d59318fabb1b96 is incorrect.
```

**Comment by DmytroLitvinov** [comment]
Привет, @egorsmkv.
Спасибо комментарий. Писал разработчикам kuna о таком же "баге".
Написали, чтоб я синхронизировал своё локальное время. 
Через раз, когда вызываю User methods, то я тоже получаю такую ошибку.
Попробую улушчить код. Возможно милисекунды дают о себе знать.

**Comment by egorsmkv** [comment]
@DmytroLitvinov 

Я для примера сделал без библиотеки вызов:

```
import time
import requests
import hmac
import hashlib
import base64
import binascii

ACCESS_KEY = 'twsWy4p5Tg5yRC7eYPvJpzKxCmHJ7M72J0ziyeTC'
SECRET_KEY = 'erPKGRqmeycN1nYamx3eiibhY4DguHi7E1uI0MLe'

WORK_PAIR = 'btcuah'

def tonce():
	t = '{0:.3f}'.format(time.time())
	return int(t.replace('.', ''))


def signature(http_verb, uri, params):
	secretBytes = str.encode(SECRET_KEY)

	msg = '{}|{}|{}'.format(http_verb, uri, params)
	msgBytes = str.encode(msg)
	
	dig = hmac.new(secretBytes, msg=msgBytes, digestmod=hashlib.sha256).digest()

	return str(binascii.hexlify(dig), 'ascii')


def me():
	api_host = 'https://kuna.io'
	uri = '/api/v2/members/me'
	params = 'access_key={}&tonce={}'.format(ACCESS_KEY, tonce())
	sign = '&signature={}'.format(signature('GET', uri, params))

	url = api_host + uri + '?' + params + sign

	data = requests.get(url)

	return data.json()
```

Вызов работает правильно.

**Comment by DmytroLitvinov** [comment]
Спасибо за предоставленный код. Разобрался в чем проблема была. Оказывается, для генерации `signature` нужен корректный `params`. 
Из документации:  "..params — отсортированные параметры, включая access_key и tonce, но без подписи".
Главное слово тут "отсортированные". Поэтому через раз срабатывало.
Спасибо за участвие :)
