### ISSUE TITLE
Add support for API v3

### ISSUE THREAD

**Issue by vhdmsm** [DmytroLitvinov/kuna#71]
Hi,

As I'm seeing, the last update of this package is for 2018 and since then, API has changed! could you please release an update to cover changes?

**Comment by DmytroLitvinov** [comment]
Hi @vhdmsm ,

Thanks for mention about changes in API. Need to check it and provide new version at PyPi.
Also, PR are welcome :)

**Comment by DmytroLitvinov** [comment]
I see that you [have forked and provided some changes](https://github.com/vhdmsm/kuna/commit/5e3390484bd23b9349a9f1a68821db73634cf44c) at library.

**Comment by DmytroLitvinov** [comment]
Hi everyone.
Seems like Kuna provided a new version of [API (v3)](https://docs.kuna.io/docs/getting-started).
That library uses API v2 and it still works. If someone feels a power to update code of library to support latest API version, please feel free to open PR I am happy to merge it and release it.
